import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'vi';

export const translations = {
  en: {
    appName: 'DocuMax',
    dashboard: 'Dashboard',
    scanner: 'Scanner',
    pdfTools: 'PDF Tools',
    converters: 'Converters',
    spreadsheets: 'Spreadsheets',
    qrBarcode: 'QR & Barcode',
    settings: 'Settings',
    admin: 'Admin',
    recentDocuments: 'Recent Documents',
    allDocuments: 'All Documents',
    noDocuments: 'No documents found. Start by scanning or uploading a file!',
    uploadFile: 'Upload File',
    dragDrop: 'Drag and drop your files here, or click to browse',
    search: 'Search...',
    filterAll: 'All Files',
    filterPdf: 'PDFs',
    filterImages: 'Images',
    filterSheets: 'Spreadsheets',
    filterText: 'Text',
    billing: 'Billing',
    subscription: 'Subscription',
    currentTier: 'Current Tier',
    upgrade: 'Upgrade',
    freeTier: 'Free',
    proTier: 'Pro',
    businessTier: 'Business',
    guestMode: 'Guest Mode',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    googleSignIn: 'Sign in with Google',
    appleSignIn: 'Sign in with Apple',
    emailSignIn: 'Sign in with Email',
    loading: 'Loading...',
    processing: 'Processing...',
    saveLocal: 'Save locally',
    saveCloud: 'Save to Cloud',
    saveGoogleDrive: 'Save to Google Drive',
    localOnly: 'Local Only',
    cloudSynced: 'Synced',
    cameraCapture: 'Capture Document',
    edgeDetection: 'Edge Detection',
    crop: 'Crop',
    enhance: 'Enhance',
    grayscale: 'Grayscale',
    blackWhite: 'B&W',
    ocr: 'OCR (Extract Text)',
    ocrResult: 'OCR Result',
    copyText: 'Copy Text',
    textCopied: 'Text copied to clipboard!',
    mergePdf: 'Merge PDFs',
    splitPdf: 'Split PDF',
    compressPdf: 'Compress PDF',
    watermarkPdf: 'Watermark PDF',
    signPdf: 'Sign PDF',
    passwordPdf: 'Encrypt PDF',
    imageToPdf: 'Image to PDF',
    pdfToImage: 'PDF to Image',
    pdfToText: 'PDF to Text',
    convert: 'Convert',
    download: 'Download',
    undo: 'Undo',
    redo: 'Redo',
    language: 'Language',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    storageUsage: 'Storage Usage',
    featuresGated: 'Upgrade to unlock this feature',
    pageLimitReached: 'Free tier limit reached',
    scanCode: 'Scan QR/Barcode',
    generateCode: 'Generate QR/Barcode',
    importCsvExcel: 'Import CSV/Excel',
    exportCsvExcel: 'Export CSV/Excel',
    auditLogs: 'Audit Logs',
    analytics: 'Analytics',
    userManagement: 'Users',
    activeUsers: 'Active Users',
    totalOcrRuns: 'Total OCR Runs',
    revenue: 'Monthly Revenue',
  },
  es: {
    appName: 'DocuMax',
    dashboard: 'Panel',
    scanner: 'Escáner',
    pdfTools: 'Herramientas PDF',
    converters: 'Convertidores',
    spreadsheets: 'Hojas de Cálculo',
    qrBarcode: 'QR y Código de Barras',
    settings: 'Ajustes',
    admin: 'Admin',
    recentDocuments: 'Documentos Recientes',
    allDocuments: 'Todos los Documentos',
    noDocuments: 'No se encontraron documentos. ¡Comienza escaneando o subiendo un archivo!',
    uploadFile: 'Subir Archivo',
    dragDrop: 'Arrastra y suelta tus archivos aquí, o haz clic para buscar',
    search: 'Buscar...',
    filterAll: 'Todos los Archivos',
    filterPdf: 'PDFs',
    filterImages: 'Imágenes',
    filterSheets: 'Hojas de cálculo',
    filterText: 'Texto',
    billing: 'Facturación',
    subscription: 'Suscripción',
    currentTier: 'Plan Actual',
    upgrade: 'Actualizar',
    freeTier: 'Gratuito',
    proTier: 'Pro',
    businessTier: 'Negocios',
    guestMode: 'Modo Invitado',
    signIn: 'Iniciar Sesión',
    signOut: 'Cerrar Sesión',
    googleSignIn: 'Iniciar sesión con Google',
    appleSignIn: 'Iniciar sesión con Apple',
    emailSignIn: 'Iniciar sesión con Correo',
    loading: 'Cargando...',
    processing: 'Procesando...',
    saveLocal: 'Guardar localmente',
    saveCloud: 'Guardar en la Nube',
    saveGoogleDrive: 'Guardar en Google Drive',
    localOnly: 'Solo Local',
    cloudSynced: 'Sincronizado',
    cameraCapture: 'Capturar Documento',
    edgeDetection: 'Detección de Bordes',
    crop: 'Recortar',
    enhance: 'Mejorar',
    grayscale: 'Escala de Grises',
    blackWhite: 'Blanco y Negro',
    ocr: 'OCR (Extraer Texto)',
    ocrResult: 'Resultado de OCR',
    copyText: 'Copiar Texto',
    textCopied: '¡Texto copiado al portapapeles!',
    mergePdf: 'Combinar PDFs',
    splitPdf: 'Dividir PDF',
    compressPdf: 'Comprimir PDF',
    watermarkPdf: 'Marca de Agua',
    signPdf: 'Firmar PDF',
    passwordPdf: 'Cifrar PDF',
    imageToPdf: 'Imagen a PDF',
    pdfToImage: 'PDF a Imagen',
    pdfToText: 'PDF a Texto',
    convert: 'Convertir',
    download: 'Descargar',
    undo: 'Deshacer',
    redo: 'Rehacer',
    language: 'Idioma',
    theme: 'Tema',
    darkMode: 'Modo Oscuro',
    lightMode: 'Modo Claro',
    storageUsage: 'Uso de Almacenamiento',
    featuresGated: 'Actualiza para desbloquear esta función',
    pageLimitReached: 'Límite de plan gratuito alcanzado',
    scanCode: 'Escanear QR/Código',
    generateCode: 'Generar QR/Código',
    importCsvExcel: 'Importar CSV/Excel',
    exportCsvExcel: 'Exportar CSV/Excel',
    auditLogs: 'Registros de Auditoría',
    analytics: 'Estadísticas',
    userManagement: 'Usuarios',
    activeUsers: 'Usuarios Activos',
    totalOcrRuns: 'Ejecuciones OCR',
    revenue: 'Ingresos Mensuales',
  },
  fr: {
    appName: 'DocuMax',
    dashboard: 'Tableau de bord',
    scanner: 'Scanner',
    pdfTools: 'Outils PDF',
    converters: 'Convertisseurs',
    spreadsheets: 'Feuilles de calcul',
    qrBarcode: 'QR & Code-barres',
    settings: 'Paramètres',
    admin: 'Admin',
    recentDocuments: 'Documents Récents',
    allDocuments: 'Tous les Documents',
    noDocuments: 'Aucun document trouvé. Commencez par scanner ou téléverser un fichier !',
    uploadFile: 'Téléverser un fichier',
    dragDrop: 'Glissez-déposez vos fichiers ici, ou cliquez pour parcourir',
    search: 'Rechercher...',
    filterAll: 'Tous les fichiers',
    filterPdf: 'PDFs',
    filterImages: 'Images',
    filterSheets: 'Feuilles',
    filterText: 'Texte',
    billing: 'Facturation',
    subscription: 'Abonnement',
    currentTier: 'Offre Actuelle',
    upgrade: 'Mettre à niveau',
    freeTier: 'Gratuit',
    proTier: 'Pro',
    businessTier: 'Entreprise',
    guestMode: 'Mode Invité',
    signIn: 'Se connecter',
    signOut: 'Se déconnecter',
    googleSignIn: 'Se connecter avec Google',
    appleSignIn: 'Se connecter avec Apple',
    emailSignIn: 'Se connecter par Email',
    loading: 'Chargement...',
    processing: 'Traitement...',
    saveLocal: 'Enregistrer localement',
    saveCloud: 'Enregistrer sur le Cloud',
    saveGoogleDrive: 'Enregistrer sur Google Drive',
    localOnly: 'Local uniquement',
    cloudSynced: 'Synchronisé',
    cameraCapture: 'Capturer le document',
    edgeDetection: 'Détection de contours',
    crop: 'Rogner',
    enhance: 'Améliorer',
    grayscale: 'Niveaux de gris',
    blackWhite: 'Noir & Blanc',
    ocr: 'OCR (Extraire le texte)',
    ocrResult: 'Résultat OCR',
    copyText: 'Copier le texte',
    textCopied: 'Texte copié dans le presse-papiers !',
    mergePdf: 'Fusionner des PDFs',
    splitPdf: 'Diviser un PDF',
    compressPdf: 'Compresser un PDF',
    watermarkPdf: 'Filigrane PDF',
    signPdf: 'Signer un PDF',
    passwordPdf: 'Chiffrer un PDF',
    imageToPdf: 'Image en PDF',
    pdfToImage: 'PDF en Image',
    pdfToText: 'PDF en Texte',
    convert: 'Convertir',
    download: 'Télécharger',
    undo: 'Annuler',
    redo: 'Rétablir',
    language: 'Langue',
    theme: 'Thème',
    darkMode: 'Mode sombre',
    lightMode: 'Mode clair',
    storageUsage: 'Stockage Utilisé',
    featuresGated: 'Abonnez-vous pour débloquer cette fonctionnalité',
    pageLimitReached: 'Limite de l\'offre gratuite atteinte',
    scanCode: 'Scanner QR/Code-barres',
    generateCode: 'Générer QR/Code-barres',
    importCsvExcel: 'Importer CSV/Excel',
    exportCsvExcel: 'Exporter CSV/Excel',
    auditLogs: 'Journaux d\'audit',
    analytics: 'Analyses',
    userManagement: 'Utilisateurs',
    activeUsers: 'Utilisateurs Actifs',
    totalOcrRuns: 'OCR Exécutés',
    revenue: 'Revenu Mensuel',
  },
  de: {
    appName: 'DocuMax',
    dashboard: 'Dashboard',
    scanner: 'Scanner',
    pdfTools: 'PDF-Tools',
    converters: 'Konverter',
    spreadsheets: 'Tabellen',
    qrBarcode: 'QR & Barcode',
    settings: 'Einstellungen',
    admin: 'Admin',
    recentDocuments: 'Letzte Dokumente',
    allDocuments: 'Alle Dokumente',
    noDocuments: 'Keine Dokumente gefunden. Scannen oder laden Sie eine Datei hoch!',
    uploadFile: 'Datei hochladen',
    dragDrop: 'Dateien hierhin ziehen oder klicken zum Auswählen',
    search: 'Suchen...',
    filterAll: 'Alle Dateien',
    filterPdf: 'PDFs',
    filterImages: 'Bilder',
    filterSheets: 'Tabellen',
    filterText: 'Text',
    billing: 'Abrechnung',
    subscription: 'Abonnement',
    currentTier: 'Aktueller Tarif',
    upgrade: 'Upgrade',
    freeTier: 'Kostenlos',
    proTier: 'Pro',
    businessTier: 'Business',
    guestMode: 'Gastmodus',
    signIn: 'Anmelden',
    signOut: 'Abmelden',
    googleSignIn: 'Mit Google anmelden',
    appleSignIn: 'Mit Apple anmelden',
    emailSignIn: 'Mit E-Mail anmelden',
    loading: 'Laden...',
    processing: 'Verarbeiten...',
    saveLocal: 'Lokal speichern',
    saveCloud: 'In Cloud speichern',
    saveGoogleDrive: 'In Google Drive speichern',
    localOnly: 'Nur lokal',
    cloudSynced: 'Synchronisiert',
    cameraCapture: 'Dokument aufnehmen',
    edgeDetection: 'Randerkennung',
    crop: 'Zuschneiden',
    enhance: 'Verbessern',
    grayscale: 'Graustufen',
    blackWhite: 'Schwarz-Weiß',
    ocr: 'OCR (Text extrahieren)',
    ocrResult: 'OCR-Ergebnis',
    copyText: 'Text kopieren',
    textCopied: 'Text in Zwischenablage kopiert!',
    mergePdf: 'PDFs zusammenführen',
    splitPdf: 'PDF teilen',
    compressPdf: 'PDF komprimieren',
    watermarkPdf: 'Wasserzeichen hinzufügen',
    signPdf: 'PDF unterschreiben',
    passwordPdf: 'PDF verschlüsseln',
    imageToPdf: 'Bild zu PDF',
    pdfToImage: 'PDF zu Bild',
    pdfToText: 'PDF zu Text',
    convert: 'Konvertieren',
    download: 'Herunterladen',
    undo: 'Rückgängig',
    redo: 'Wiederholen',
    language: 'Sprache',
    theme: 'Design',
    darkMode: 'Dunkelmodus',
    lightMode: 'Hellmodus',
    storageUsage: 'Speicherbelegung',
    featuresGated: 'Upgrade erforderlich für diese Funktion',
    pageLimitReached: 'Limit des kostenlosen Tarifs erreicht',
    scanCode: 'QR/Barcode scannen',
    generateCode: 'QR/Barcode erstellen',
    importCsvExcel: 'CSV/Excel importieren',
    exportCsvExcel: 'CSV/Excel exportieren',
    auditLogs: 'Audit-Protokolle',
    analytics: 'Analysen',
    userManagement: 'Benutzer',
    activeUsers: 'Aktive Nutzer',
    totalOcrRuns: 'OCR-Ausführungen',
    revenue: 'Monatlicher Umsatz',
  },
  vi: {
    appName: 'DocuMax',
    dashboard: 'Trang chủ',
    scanner: 'Quét tài liệu',
    pdfTools: 'Công cụ PDF',
    converters: 'Chuyển đổi',
    spreadsheets: 'Bảng tính',
    qrBarcode: 'QR & Mã vạch',
    settings: 'Cài đặt',
    admin: 'Quản trị',
    recentDocuments: 'Tài liệu gần đây',
    allDocuments: 'Tất cả tài liệu',
    noDocuments: 'Không tìm thấy tài liệu nào. Hãy quét hoặc tải lên một tệp tin!',
    uploadFile: 'Tải tệp lên',
    dragDrop: 'Kéo thả tài liệu vào đây hoặc click để duyệt file',
    search: 'Tìm kiếm...',
    filterAll: 'Tất cả',
    filterPdf: 'PDF',
    filterImages: 'Hình ảnh',
    filterSheets: 'Bảng tính',
    filterText: 'Văn bản',
    billing: 'Thanh toán',
    subscription: 'Gói dịch vụ',
    currentTier: 'Gói hiện tại',
    upgrade: 'Nâng cấp',
    freeTier: 'Miễn phí',
    proTier: 'Pro',
    businessTier: 'Doanh nghiệp',
    guestMode: 'Chế độ khách',
    signIn: 'Đăng nhập',
    signOut: 'Đăng xuất',
    googleSignIn: 'Đăng nhập với Google',
    appleSignIn: 'Đăng nhập với Apple',
    emailSignIn: 'Đăng nhập bằng Email',
    loading: 'Đang tải...',
    processing: 'Đang xử lý...',
    saveLocal: 'Lưu trên thiết bị',
    saveCloud: 'Lưu trên Cloud',
    saveGoogleDrive: 'Lưu vào Google Drive',
    localOnly: 'Chỉ ngoại tuyến',
    cloudSynced: 'Đã đồng bộ',
    cameraCapture: 'Chụp tài liệu',
    edgeDetection: 'Tự động nhận diện cạnh',
    crop: 'Cắt chỉnh',
    enhance: 'Làm nét',
    grayscale: 'Ảnh xám',
    blackWhite: 'Trắng đen',
    ocr: 'OCR (Trích xuất chữ)',
    ocrResult: 'Kết quả OCR',
    copyText: 'Sao chép chữ',
    textCopied: 'Đã sao chép chữ vào bộ nhớ tạm!',
    mergePdf: 'Ghép file PDF',
    splitPdf: 'Cắt file PDF',
    compressPdf: 'Nén file PDF',
    watermarkPdf: 'Đóng dấu PDF',
    signPdf: 'Ký tên PDF',
    passwordPdf: 'Đặt mật khẩu PDF',
    imageToPdf: 'Ảnh sang PDF',
    pdfToImage: 'PDF sang Ảnh',
    pdfToText: 'PDF sang Văn bản',
    convert: 'Chuyển đổi',
    download: 'Tải xuống',
    undo: 'Hoàn tác',
    redo: 'Làm lại',
    language: 'Ngôn ngữ',
    theme: 'Giao diện',
    darkMode: 'Chế độ tối',
    lightMode: 'Chế độ sáng',
    storageUsage: 'Dung lượng đã dùng',
    featuresGated: 'Nâng cấp gói dịch vụ để mở khóa tính năng này',
    pageLimitReached: 'Đã đạt giới hạn gói miễn phí',
    scanCode: 'Quét QR/Mã vạch',
    generateCode: 'Tạo QR/Mã vạch',
    importCsvExcel: 'Nhập dữ liệu Excel/CSV',
    exportCsvExcel: 'Xuất dữ liệu Excel/CSV',
    auditLogs: 'Nhật ký hệ thống',
    analytics: 'Thống kê',
    userManagement: 'Thành viên',
    activeUsers: 'Số người dùng hoạt động',
    totalOcrRuns: 'Lượt trích xuất chữ',
    revenue: 'Doanh thu tháng',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations.en;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language | null;
    if (saved) return saved;
    
    // Auto-detect browser language
    const browserLang = navigator.language.slice(0, 2);
    if (['en', 'es', 'fr', 'de', 'vi'].includes(browserLang)) {
      return browserLang as Language;
    }
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = translations[language] || translations.en;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
